### ISSUE TITLE
Error from submitting timesheet due to permission

### ISSUE THREAD

**Issue by siewyeng** [ThorpeJosh/tp-timesheet#110]
<img width="1751" alt="Screenshot 2023-06-16 at 9 48 47 AM" src="https://github.com/ThorpeJosh/tp-timesheet/assets/59408288/92c87ed7-6e03-44c3-858e-0b6865620f13">

**Comment by ThorpeJosh** [comment]
Need to remove this line. Seems they won't let 'Billable' be set anymore.

https://github.com/ThorpeJosh/tp-timesheet/blob/d2b605a0078a9cb47f17d049a367ae3bcb0c59d3/tp_timesheet/clockify_timesheet.py#L75C24-L75C24

**Comment by siewyeng** [comment]
> Need to remove this line. Seems they won't let 'Billable' be set anymore.
> 
> https://github.com/ThorpeJosh/tp-timesheet/blob/d2b605a0078a9cb47f17d049a367ae3bcb0c59d3/tp_timesheet/clockify_timesheet.py#L75C24-L75C24

Wow thanks! How did you find out from the error image? :O

**Comment by ThorpeJosh** [comment]
No problem. I saw in logs it attempted to post a json with `billable: true` and it got a 501 error stating that we don't have permission to update the billability.

500 series errors are server side (clockify servers) and usually related to incorrect parameters, features not implemented, server malfunctions, etc. In this case luckily the message was informative.

**Comment by changukshin** [comment]
#111
