### ISSUE TITLE
[Discussion]Improvement of alert(notification)

### ISSUE THREAD

**Issue by changukshin** [ThorpeJosh/tp-timesheet#12]
Current alert feature is based upon a OSX feature(AppleScript).

So some strict regulations exist like,
- we can't modify small icon(thumbnail) of it.
- we can't also attach link to it. (click to open a screenshot or, open browser to bring to an website)

Maybe there are some third-party notification libraries, I will figure it out which options do we have.

At this time we didn't decide the exact functionality which the notification would have, these are possible options(including but not limited to)
- Notification has a link of screenshot of submission page, so we can debug(dev) or check(user) the submission with it.

Any suggestions are welcome, always.

**Comment by changukshin** [comment]
Possible option of notification library

https://github.com/Jorricks/macos-notifications

**Comment by ThorpeJosh** [comment]
I think the macos-notifications python library is a great idea. Much more flexible and maintainable than calling a shell command.

Adding the ability to quickly see the final submission page in the notification would be great.

**Comment by changukshin** [comment]
I think the project(macos-notifications) is somehow broken. I can't invoke alert with it.
I'd searched some alternatives, and no luck.

I am closing this issue and let this topic postpone for next time.
Any advice / suggestions are welcome, always.
