### ISSUE TITLE
workalendar UserWarning 

### ISSUE THREAD

**Issue by changukshin** [ThorpeJosh/tp-timesheet#13]
Please refer to the below screenshot.

Do we need to address this warning or just let this warning dismissed?
Could you take a look? @siewyeng 

<img width="1733" alt="image" src="https://user-images.githubusercontent.com/6247953/193489974-2e8a2f49-379c-475e-8345-063b4faa7c42.png">

Regards,

**Comment by siewyeng** [comment]
@changukshin I think we can just ignore it. Or do you think it would be better to have it removed?

**Comment by changukshin** [comment]
At this time it is an issue for only Islamic, so I think we can either ignore it or remove it.
As a user point of view, removing the warning is better.
As a contributor point of view, as long as we can guarantee that the library works, we can ignore it.

**Comment by siewyeng** [comment]
Okay, I'll look into that! Thanks
