### ISSUE TITLE
Scheduled submissions are not successful

### ISSUE THREAD

**Issue by ThorpeJosh** [ThorpeJosh/tp-timesheet#18]
When the automated schedule has been activated, then the cli is invoked from crontab, however the submission is not successful.

The following logs from the crontab submission suggest the docker image is never deploying:
```
Date(s) (YYYY-mm-dd) to be submitted for ****@****.com: ['2022-10-05']
Pulling latest image
Cleaning up docker container
```
The following logs from a manually invoked submission show extra logs (including the "Launching docker ..."):
```
/opt/.../workalendar/core.py:436: UserWarning: Please take note that, due to arbitrary decisions, this Islamic calendar computation may be wrong.
  warnings.warn('Please take note that, due to arbitrary decisions, '
Date(s) (YYYY-mm-dd) to be submitted for *****@*****.com: ['2022-10-03', '2022-10-04', '2022-10-05', '2022-10-06', '2022-10-07']
Pulling latest image
Launching docker container for selenium backend
Saving top of timesheet to: /Users/*****/Desktop/timesheet_top_03_10_2022.png
Saving bottom of timesheet to: /Users/*****/Desktop/timesheet_bottom_03_10_2022.png
.....More "Saving top/bottom" logs
Cleaning up docker container
```

**Comment by ThorpeJosh** [comment]
@lamchuntat @siewyeng @changukshin 
Any takers?

**Comment by changukshin** [comment]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/6247953/194018056-7be9d4b7-33dc-4711-8ff6-f1d4e2f70ecc.png">

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/6247953/194018310-7cb92ae7-d097-49d3-92fe-d54c607f7be4.png">

It looks like automated process(daemon) doesn't have permission to open `docker-credential-desktop` program.

The crontab line should know the path of `docker-credential-desktop` (which is /usr/local/bin/ for me)

This functionality was worked last time, right?
I think we have to figure out which commit harm this functionality.

Any Idea? @ThorpeJosh @siewyeng @lamchuntat
