### ISSUE TITLE
Date input does not support shorthand year

### ISSUE THREAD

**Issue by ThorpeJosh** [ThorpeJosh/tp-timesheet#19]
```tp-timesheet --start 03/10/22``` results in the following error:
```
ValueError: time data '03/10/22' does not match format '%d/%m/%Y'
```

Desired behavior is to support this shorthand date format as well as the full '03/10/2022'.
Also should test '3/10/22' or '1/1/23' formats.

**Comment by changukshin** [comment]
Processed by #22
