### ISSUE TITLE
Sanity check date prior to submission

### ISSUE THREAD

**Issue by ThorpeJosh** [ThorpeJosh/tp-timesheet#20]
Suggest adding a sanity check to ensure the date is +/- 7 days from current date to avoid accidental submissions.

**Comment by changukshin** [comment]
Possible implementation options.

1. Strictly restricting to the +/- n days.
  1-1. when user inputs the date exceed n days, print error message and abort the program.
    1-1-1. User CANNOT submit the timesheet exceed n days.
    1-1-2. User can submit the timesheet exceed n days but user need to pass one more cli options.

2. get confirm of user
  2-1. when user inputs the date exceed n days, print confirm message to get confirm of user(Y/N).
         (confirm message should have no default option. To make sure the submission is correct., i.e. if user inputs nothing, re-print confirm message or abort the program.)

I think 2-1 is proper way to process this.
any comments welcome.

**Comment by ThorpeJosh** [comment]
Agree. Confirmation with a [y/N] so an accidental <enter> aborts.

**Comment by changukshin** [comment]
On it.

**Comment by buttercutter** [comment]
@changukshin Any idea if I could use https://github.com/philzook58/z3_tutorial/blob/master/Z3%20Tutorial.ipynb to solve this ?
