### ISSUE TITLE
Unit tests for handling of dates.

### ISSUE THREAD

**Issue by ThorpeJosh** [ThorpeJosh/tp-timesheet#21]
Would be great to get some unit tests for the date algorithm.

Test cases to cover:
- [x] Given strings of different formats 'd/m/yy', 'dd/m/yyyy', 'd/mm/yy', etc that the parse is correct. (#26)
- [x] Given dates outside of +/- 7days from today, then an appropriate error is raised.
- [x] Given date range then ensure dates account for weekends and public holidays correctly

**Comment by changukshin** [comment]
Listed some on contents of #22

**Comment by ThorpeJosh** [comment]
First unit test completed in #26
