### ISSUE TITLE
Logger defined multiple times

### ISSUE THREAD

**Issue by lamchuntat** [ThorpeJosh/tp-timesheet#35]
<img width="1346" alt="Screenshot 2022-10-11 at 4 47 46 PM" src="https://user-images.githubusercontent.com/67894173/195047256-d19da8d9-a91b-4b6c-9cdd-0bd65707b160.png">

Getting this issue after running pylint. Tried to fix by removing the `logger = logging.getLogger(__name__)` line in config, ended up breaking the code.

**Comment by ThorpeJosh** [comment]
change the input variable name for `def init_logger(logger)` to something else. logger is overriding the global logger you mentioned above.
