### ISSUE TITLE
[bug] Submission failed : selenium unable to locate `input` element

### ISSUE THREAD

**Issue by changukshin** [ThorpeJosh/tp-timesheet#49]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/6247953/199371580-2860d99e-0213-4a03-9d63-3fc95fd47d08.png">

This could be a temporary issue.
But still needed to be handled.

Possible options.
- retry
- notification

**Comment by siewyeng** [comment]
@siewyeng will work on raising notifications in case of failure
