### ISSUE TITLE
Exception during submission

### ISSUE THREAD

**Issue by changukshin** [ThorpeJosh/tp-timesheet#56]
<img width="743" alt="stacktrace" src="https://user-images.githubusercontent.com/6247953/201247321-97fd83ba-e0c2-4c34-8c97-ac34c8e6e454.png">

@ThorpeJosh @siewyeng @lamchuntat

**Comment by changukshin** [comment]
cmd : `tp-timesheet -s today -n`

**Comment by ThorpeJosh** [comment]
@changukshin This should be resolved now. Can you please confirm on lastest version and reopen if it is still occuring?

**Comment by changukshin** [comment]
Confirm. Working as expected.
