### ISSUE TITLE
Adding --version argument.

### ISSUE THREAD

**Issue by changukshin** [ThorpeJosh/tp-timesheet#62]
This is needed to check the installed version is latest.
The version message should get the actual version from [tp_timesheet/__init__.py](https://github.com/ThorpeJosh/tp-timesheet/blob/642552e9d6faa86c53a75479ba85a3eac797b84c/tp_timesheet/__init__.py#L5).

As we already reserved `-v` to `verbose`, we need to decide that the shorten argument `-v` goes to whether `--verbose` or `--version`.
Opinion, discussion, any idea is welcome as always.

**Comment by ThorpeJosh** [comment]
This is logical. `--version` makes sense and is what everything else uses.

`-v`/`--verbose` can be kept as is. It won't conflict with version

**Comment by changukshin** [comment]
Totally agreed with you.

Status : need discuss -> wait for taker
