### ISSUE TITLE
[Feature Suggestion]Automated alert feature

### ISSUE THREAD

**Issue by changukshin** [ThorpeJosh/tp-timesheet#7]
Is it useful if I add a feature which shows an alert when the automated submission is done?

Please refer attached screenshot.

If confirmed, I will write the code and make PR.

Regards,

<img width="703" alt="alert" src="https://user-images.githubusercontent.com/6247953/192675708-2dd3f2a3-3897-4551-87ec-6f683e2bdc1a.png">

**Comment by changukshin** [comment]
Any advise and revising is always welcome. :)

**Comment by ThorpeJosh** [comment]
That would be great!

Is the picture customisable? Maybe can include a screenshot of the successful submission.

**Comment by changukshin** [comment]
That would be also great!!
I think I can add the picture. I will figure it out.

For this thread and first PR, I want to add the feature of alert as I first need to be familiar with this project.
Let's deal with the feature you suggested onto the other issue thread/PR after I add just a (non-fancy) alert.

Kindly confirm this. :)

**Comment by ThorpeJosh** [comment]
Sounds good. Multiple PRs is more agile.

**Comment by changukshin** [comment]
Closing this issue as the notification feature was added with #9.
As we discussed above, we discuss later with the other thread regarding to the screenshot and information of the alert.
